{{ if .Values.ubiquia.components.util.workbench.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: ubiquia-core-flow-service
  labels:
    component: ubiquia-core-flow-service
spec:
  type: ClusterIP
  ports:
    - name: http
      port: {{ .Values.convenience.variables.spring.port }}
      targetPort: http
      protocol: TCP
  selector:
    component: ubiquia-core-flow-service
{{ end }}