logging:
  ubiquia: INFO

ubiquia:
  cluster:
  agent:
    database: 
      h2:
        enabled: false
      yugabyte:
        enabled: true
    flowService:
      bootstrap:
        enabled: true
        beliefState:
          deployments:
        graph:
          deployments:
            - name: ubiquia-workbench
              version:
                major: 1
                minor: 0
                patch: 0
    storage:
      minio:
        enabled: false
        
  components:
    core:
      beliefStateGeneratorService:
        image:
          registry: docker.io/ubiquia
          repository: core-belief-state-generator-service
          tag: latest
      communicationService:
        image:
          registry: docker.io/ubiquia
          repository: core-communication-service
          tag: latest
      flowService:
        image:
          registry: docker.io/ubiquia
          repository: core-flow-service
          tag: latest
    test:
      beliefStateGeneratorService:
        image:
          registry: docker.io/ubiquia
          repository: test-belief-state-generator-service
          tag: latest
      
infrastructure:
  image:
    pullPolicy: Never

# yugabyte:

#   tserver:
#     serverBroadcastAddress: "192.168.200.56:30910"

#   master:
#     serverBroadcastAddress: 192.168.200.56:30710"