apiVersion: v1
kind: Service
metadata:
  name: ubiquia-core-communication-service
  labels:
    component: ubiquia-core-communication-service
spec:
  type: NodePort
  ports:
    - name: http
      port: {{ .Values.convenience.variables.spring.port }}
      targetPort: http
      protocol: TCP
      nodePort: 30080
  selector:
    component: ubiquia-core-communication-service