apiVersion: v1
kind: ConfigMap
metadata:
  name: ubiquia-core-belief-state-generator-config
data:
  application.yaml: |

    logging:
      level:
        org.ubiquia: {{ .Values.logging.ubiquia }}

    management:
      endpoint:
        info:
          enabled: true
          java:
            enabled: true
          build:
            enabled: true
          health:
            probes:
              enabled: true
            show-components: always
            show-details: always
          prometheus:
            enabled: true
      endpoints:
        web:
          exposure:
            include: info, prometheus, health
      metrics:
        tags:
          application: ${spring.application.name}

    spring:
      server:
        port: {{ .Values.convenience.variables.spring.port }}
  
      application:
        name: belief-state-generator-service
      jackson:
        date-format: "yyyy-MM-dd'T'HH:mm:ss.SSSSSS'Z'"

    springdoc:
      swagger-ui:
        path: {{ .Values.convenience.variables.spring.swaggerDocs }}
        enabled: true

    ubiquia:
      agent:
        id: {{ .Values.ubiquia.agent.id }}
        database: 
          h2: 
            enabled: {{ .Values.ubiquia.agent.database.h2.enabled }}
          yugabyte: 
            enabled: {{ .Values.ubiquia.agent.database.yugabyte.enabled }}
        storage:
          minio:
            enabled: {{ .Values.ubiquia.agent.storage.minio.enabled }}
      beliefStateGeneratorService:
        libraries:
          directory:
            path: "/app/resources/belief-state-libs"
        template:
          filepath:
            dto: "/app/resources/template/java/dto"
            entity: "/app/resources/template/java/entity"
        uber:
          jars:
            path: "/belief-state-jars/"        
      flow:
        service:
          port: {{ .Values.convenience.variables.spring.port }}
          url: http://ubiquia-core-flow-service
      jdkVersion: 21 # TODO: Make sure this is controlled by the top-level gradle.properties variable
      kubernetes:
        enabled: true
        namespace: {{ .Release.Namespace }}      