apiVersion: v1
kind: Service
metadata:
  name: yb-ysql-nodeport
spec:
  type: NodePort
  selector:
    app: yb-tserver
  ports:
    - name: ysql
      port: 5433
      targetPort: 5433
      protocol: TCP
      nodePort: 30433
