apiVersion: v1
kind: Service
metadata:
  name: yb-tserver-ui-nodeport
  namespace: ubiquia
spec:
  type: NodePort
  selector:
    app: yb-tserver
  ports:
    - name: tserver-ui
      port: 9000
      targetPort: 9000
      protocol: TCP
      nodePort: 30900
