apiVersion: v1
kind: Service
metadata:
  name: yb-ysql-nodeport
  namespace: ubiquia
spec:
  type: NodePort
  selector:
    app: yb-tserver
  ports:
    - name: ysql
      port: 5443
      targetPort: 5443
      protocol: TCP
      nodePort: 30433
